/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author M E L I A
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Iventaris extends javax.swing.JPanel {

    /**
     * Creates new form Iventaris
     */
    
    public Statement st;
    public ResultSet rs;
    Connection connection = config.koneksi.getConnection();
    
    public Iventaris() {
        initComponents();
        TampilData();
    }
    
    private void Bersih() {
        t_idproduk.setText("");
        t_namaproduk.setText("");
        t_harga.setText("");
        t_stok.setText("");
        
        btn_simpan.setText("Simpan");
        t_idproduk.setEditable(true);
    }
    
    private void CariData() {
        try {
            st = connection.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_produk WHERE " +
                combo_cari.getSelectedItem().toString() + 
                " LIKE '%" + t_caridata.getText() + "%'");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("Id_produk");
            model.addColumn("Id_jenis");
            model.addColumn("Id_supplier");
            model.addColumn("Nama_produk");
            model.addColumn("Harga");
            model.addColumn("Stok");
            
            int no = 1;
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
               Object[] data = {
                   no ++,
                   rs.getString("Id_produk"),
                   rs.getString("Id_jenis"),
                   rs.getString("Id_supplier"),
                   rs.getString("Nama_produk"),
                   rs.getString("Harga"),
                   rs.getString("Stok")
               };
               model.addRow(data);
               tabel_data.setModel(model);
            }
            
            
        } catch (Exception e) {
        }
    }
    
    private void TampilData() {
        try {
            st = connection.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_produk");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("Id_produk");
            model.addColumn("Id_jenis");
            model.addColumn("Id_supplier");
            model.addColumn("Nama_produk");
            model.addColumn("Harga");
            model.addColumn("Stok");
            
            int no = 1;
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
               Object[] data = {
                   no ++,
                   rs.getString("Id_produk"),
                   rs.getString("Id_jenis"),
                   rs.getString("Id_supplier"),
                   rs.getString("Nama_produk"),
                   rs.getString("Harga"),
                   rs.getString("Stok")
               };
               model.addRow(data);
               tabel_data.setModel(model);
            }
            
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        l_barang = new javax.swing.JLabel();
        l_idproduk = new javax.swing.JLabel();
        l_idjenis = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        l_supplier = new javax.swing.JLabel();
        l_namaproduk = new javax.swing.JLabel();
        l_harga = new javax.swing.JLabel();
        l_stok = new javax.swing.JLabel();
        t_idproduk = new javax.swing.JTextField();
        combo_supplier = new javax.swing.JComboBox<>();
        t_namaproduk = new javax.swing.JTextField();
        t_harga = new javax.swing.JTextField();
        t_stok = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        btn_caridata = new javax.swing.JButton();
        combo_cari = new javax.swing.JComboBox<>();
        t_caridata = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        l_barang.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        l_barang.setText("DATA BARANG ");

        l_idproduk.setText("Id_Produk");

        l_idjenis.setText("Id_Jenis");

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "brg01 ", "brg02", "brg03", " " }));

        l_supplier.setText("Id_Supplier");

        l_namaproduk.setText("Nama_Produk");

        l_harga.setText("Harga");

        l_stok.setText("Stok");

        combo_supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sup01", "sup02", "sup03", " " }));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_produk", "Id_jenis", "Id_supplier", "Nama_Produk", "Harga", "Stok"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_data);

        btn_caridata.setText("Cari Data");

        combo_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id_produk", "Id_jenis", "Id_supplier", "Nama_Produk", " " }));

        t_caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_caridataKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_idproduk)
                            .addComponent(l_idjenis)
                            .addComponent(l_supplier)
                            .addComponent(l_namaproduk)
                            .addComponent(l_harga)
                            .addComponent(l_stok))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_idproduk)
                            .addComponent(combo_jenis, 0, 316, Short.MAX_VALUE)
                            .addComponent(combo_supplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_namaproduk)
                            .addComponent(t_harga)
                            .addComponent(t_stok)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(l_barang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_caridata)
                        .addGap(29, 29, 29)
                        .addComponent(combo_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(t_caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_barang)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_idproduk)
                    .addComponent(t_idproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_idjenis)
                    .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_supplier)
                    .addComponent(combo_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_namaproduk)
                    .addComponent(t_namaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_harga)
                    .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_stok)
                    .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_caridata)
                    .addComponent(t_caridata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            st = connection.createStatement();
            if (t_idproduk.getText().equals("") || 
                    combo_jenis.getSelectedItem() == null ||
                    combo_supplier.getSelectedItem() == null ||
                    t_namaproduk.getText().equals("") || 
                    t_harga.getText().equals("") || 
                    t_stok.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            //aksi simpan data
            if (btn_simpan.getText() == "Simpan") {
                String cek ="SELECT * FROM tb_produk WHERE Id_produk = '" + t_idproduk.getText() + "'";
                rs = st.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Maaf..Id_produk ini sudah ada");
                } else {
                    String sql = "INSERT INTO tb_produk VALUES ('" + t_idproduk.getText() + 
                            "','" + combo_jenis.getSelectedItem() +
                            "','" + combo_supplier.getSelectedItem() +      
                            "','" + t_namaproduk.getText() +
                            "','" + t_harga.getText() +
                            "','" + t_stok.getText() + "')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                    Bersih();
                    TampilData();
                }
            }else {
                //aksi ubah data
                    String update = "UPDATE tb_produk SET Nama_produk = '" + t_namaproduk.getText() +
                            "', Harga = '" + t_harga.getText() +
                            "', Stok = '" + t_stok.getText() +       
                            "' WHERE Id_produk = '" + t_idproduk.getText() + "'";
                    st.executeLargeUpdate(update);
                    JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                    Bersih();
                    TampilData();
                    }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        t_idproduk.setText(tabel_data.getValueAt(tabel_data.getSelectedRow(), 1).toString());
        t_namaproduk.setText(tabel_data.getValueAt(tabel_data.getSelectedRow(), 4).toString());
        t_harga.setText(tabel_data.getValueAt(tabel_data.getSelectedRow(), 5).toString());
        t_stok.setText(tabel_data.getValueAt(tabel_data.getSelectedRow(), 6).toString());
        
        t_idproduk.setEditable(false);
        btn_simpan.setText("Ubah");
                
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if (t_idproduk.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus"); 
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Apakah yakin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    st = connection.createStatement();
                    String sql = "DELETE FROM tb_produk WHERE Id_produk = '" + t_idproduk.getText() + "'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    TampilData();
                    Bersih();
                    
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);
                }
                
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        Bersih();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void t_caridataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_caridataKeyPressed
       CariData();
    }//GEN-LAST:event_t_caridataKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> combo_cari;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JComboBox<String> combo_supplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l_barang;
    private javax.swing.JLabel l_harga;
    private javax.swing.JLabel l_idjenis;
    private javax.swing.JLabel l_idproduk;
    private javax.swing.JLabel l_namaproduk;
    private javax.swing.JLabel l_stok;
    private javax.swing.JLabel l_supplier;
    private javax.swing.JTextField t_caridata;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_idproduk;
    private javax.swing.JTextField t_namaproduk;
    private javax.swing.JTextField t_stok;
    private javax.swing.JTable tabel_data;
    // End of variables declaration//GEN-END:variables
}
