/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author M E L I A
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_supplier = new javax.swing.JPanel();
        t_supplier = new javax.swing.JLabel();
        ikon_supplier = new javax.swing.JLabel();
        pn_pembelian = new javax.swing.JPanel();
        t_pembelian = new javax.swing.JLabel();
        ikon_pembelian = new javax.swing.JLabel();
        pn_iventaris1 = new javax.swing.JPanel();
        t_iventaris2 = new javax.swing.JLabel();
        ikon_iventaris2 = new javax.swing.JLabel();
        pn_penjualan1 = new javax.swing.JPanel();
        t_penjualan1 = new javax.swing.JLabel();
        ikon_penjualan1 = new javax.swing.JLabel();
        pn_pembelian1 = new javax.swing.JPanel();
        t_pembelian1 = new javax.swing.JLabel();
        ikon_pembelian1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(580, 460));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_supplier.setBackground(new java.awt.Color(176, 224, 230));

        t_supplier.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        t_supplier.setText("Supplier");

        ikon_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Supplier.png"))); // NOI18N

        javax.swing.GroupLayout pn_supplierLayout = new javax.swing.GroupLayout(pn_supplier);
        pn_supplier.setLayout(pn_supplierLayout);
        pn_supplierLayout.setHorizontalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_supplierLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ikon_supplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pn_supplierLayout.setVerticalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_supplierLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ikon_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(pn_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 220, 120));

        pn_pembelian.setBackground(new java.awt.Color(176, 224, 230));

        t_pembelian.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        t_pembelian.setText("Transaksi Penjualan");

        ikon_pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Accounting.png"))); // NOI18N

        javax.swing.GroupLayout pn_pembelianLayout = new javax.swing.GroupLayout(pn_pembelian);
        pn_pembelian.setLayout(pn_pembelianLayout);
        pn_pembelianLayout.setHorizontalGroup(
            pn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pembelianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ikon_pembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pn_pembelianLayout.setVerticalGroup(
            pn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembelianLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ikon_pembelian))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(pn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, 120));

        pn_iventaris1.setBackground(new java.awt.Color(176, 224, 230));

        t_iventaris2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        t_iventaris2.setText("Iventaris");

        ikon_iventaris2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sell Stock.png"))); // NOI18N

        javax.swing.GroupLayout pn_iventaris1Layout = new javax.swing.GroupLayout(pn_iventaris1);
        pn_iventaris1.setLayout(pn_iventaris1Layout);
        pn_iventaris1Layout.setHorizontalGroup(
            pn_iventaris1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_iventaris1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ikon_iventaris2)
                .addGap(18, 18, 18)
                .addComponent(t_iventaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pn_iventaris1Layout.setVerticalGroup(
            pn_iventaris1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_iventaris1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pn_iventaris1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_iventaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ikon_iventaris2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(pn_iventaris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 120));

        pn_penjualan1.setBackground(new java.awt.Color(176, 224, 230));

        t_penjualan1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        t_penjualan1.setText("Laporan Penjualan");

        ikon_penjualan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Business Report.png"))); // NOI18N

        javax.swing.GroupLayout pn_penjualan1Layout = new javax.swing.GroupLayout(pn_penjualan1);
        pn_penjualan1.setLayout(pn_penjualan1Layout);
        pn_penjualan1Layout.setHorizontalGroup(
            pn_penjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_penjualan1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ikon_penjualan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_penjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        pn_penjualan1Layout.setVerticalGroup(
            pn_penjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_penjualan1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pn_penjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_penjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ikon_penjualan1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(pn_penjualan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 120));

        pn_pembelian1.setBackground(new java.awt.Color(176, 224, 230));

        t_pembelian1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        t_pembelian1.setText("Pembelian");

        ikon_pembelian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Egg Basket.png"))); // NOI18N

        javax.swing.GroupLayout pn_pembelian1Layout = new javax.swing.GroupLayout(pn_pembelian1);
        pn_pembelian1.setLayout(pn_pembelian1Layout);
        pn_pembelian1Layout.setHorizontalGroup(
            pn_pembelian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pembelian1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ikon_pembelian1)
                .addGap(18, 18, 18)
                .addComponent(t_pembelian1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pn_pembelian1Layout.setVerticalGroup(
            pn_pembelian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembelian1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pn_pembelian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_pembelian1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ikon_pembelian1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(pn_pembelian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 210, 120));

        jLabel1.setText("Menu > Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dash 2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 30));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ikon_iventaris2;
    private javax.swing.JLabel ikon_pembelian;
    private javax.swing.JLabel ikon_pembelian1;
    private javax.swing.JLabel ikon_penjualan1;
    private javax.swing.JLabel ikon_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_iventaris1;
    private javax.swing.JPanel pn_pembelian;
    private javax.swing.JPanel pn_pembelian1;
    private javax.swing.JPanel pn_penjualan1;
    private javax.swing.JPanel pn_supplier;
    private javax.swing.JLabel t_iventaris2;
    private javax.swing.JLabel t_pembelian;
    private javax.swing.JLabel t_pembelian1;
    private javax.swing.JLabel t_penjualan1;
    private javax.swing.JLabel t_supplier;
    // End of variables declaration//GEN-END:variables
}
